
---
- name: Windows Agent - Uninstallation
  hosts: windows #host listed in /etc/ansible/hosts

  vars_files:
    - group_vars/all

  tasks:
    - name: Stop Agent Client Collector service
      ansible.windows.win_service:
        name: AgentClientCollector
        state: stopped

    - name: Lookup Agent Client Collector product_id for uninstallation
      ansible.windows.win_shell: Get-ChildItem -Path HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall, HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall | 
        Get-ItemProperty | 
          Where-Object {$_.DisplayName -match "Agent Client Collector" } | 
            Select-Object -ExpandProperty PSChildName
      register: uninstallLookup

    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: uninstallLookup

    - name: Uninstall Agent Client Collector
      win_package:
        product_id: "{{ uninstallLookup.stdout | trim }}"
        state: absent

    - name: Cleanup agent download
      ansible.windows.win_file:
        path: '{{ ansible_env.USERPROFILE }}\Downloads\agent-client-collector-{{ version }}-windows-x64.msi'
        state: absent